/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "sunLeft_aliases.h"
#include "sunLeft.h"
#include "sunRight_aliases.h"
#include "sunRight.h"
#include "sunUp_aliases.h"
#include "sunUp.h"
#include "sunDown_aliases.h"
#include "sunDown.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "Elevation_Pin_2_aliases.h"
#include "Elevation_Pin_2.h"
#include "Elevation_Pin_3_aliases.h"
#include "Elevation_Pin_3.h"
#include "Elevation_Pin_4_aliases.h"
#include "Elevation_Pin_4.h"
#include "isr_uart_rx.h"
#include "Clock_1.h"
#include "Elevation_Pin_1_aliases.h"
#include "Elevation_Pin_1.h"
#include "Azimuth_Pin_4_aliases.h"
#include "Azimuth_Pin_4.h"
#include "Azimuth_Pin_3_aliases.h"
#include "Azimuth_Pin_3.h"
#include "Azimuth_Pin_2_aliases.h"
#include "Azimuth_Pin_2.h"
#include "Limit_Left_aliases.h"
#include "Limit_Left.h"
#include "Limit_Right_aliases.h"
#include "Limit_Right.h"
#include "Limit_Down_aliases.h"
#include "Limit_Down.h"
#include "SPIS_1.h"
#include "SPIS_1_PVT.h"
#include "isr_motor.h"
#include "UART_1.h"
#include "Limit_Up_aliases.h"
#include "Limit_Up.h"
#include "Azimuth_Pin_1_aliases.h"
#include "Azimuth_Pin_1.h"
#include "ADC_SAR_1.h"
#include "ADC_SAR_2.h"
#include "Current_Hall_In_aliases.h"
#include "Current_Hall_In.h"
#include "Voltage_Divider_In_aliases.h"
#include "Voltage_Divider_In.h"
#include "isr_spi.h"
#include "SPIS_1_IntClock.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_ExtVref_aliases.h"
#include "ADC_SAR_1_ExtVref.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "ADC_SAR_2_ExtVref_aliases.h"
#include "ADC_SAR_2_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

