/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Azimuth_Pin_1_aliases.h"
#include "Azimuth_Pin_1.h"
#include "Azimuth_Pin_4_aliases.h"
#include "Azimuth_Pin_4.h"
#include "Azimuth_Pin_3_aliases.h"
#include "Azimuth_Pin_3.h"
#include "Azimuth_Pin_2_aliases.h"
#include "Azimuth_Pin_2.h"
#include "Limit_Up_aliases.h"
#include "Limit_Up.h"
#include "Limit_Down_aliases.h"
#include "Limit_Down.h"
#include "Limit_Right_aliases.h"
#include "Limit_Right.h"
#include "Limit_Left_aliases.h"
#include "Limit_Left.h"
#include "Elevation_Pin_1_aliases.h"
#include "Elevation_Pin_1.h"
#include "Elevation_Pin_2_aliases.h"
#include "Elevation_Pin_2.h"
#include "Elevation_Pin_3_aliases.h"
#include "Elevation_Pin_3.h"
#include "Elevation_Pin_4_aliases.h"
#include "Elevation_Pin_4.h"
#include "isr_uart_rx.h"
#include "Clock_1.h"
#include "isr_motor.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

